### PR TITLE
Remove test_if_bot_is_unbchatbot test

### PR DESCRIPTION
**Pull request by vinicius0197**
## PR Description

Fix issue #42 .

### New Feature Submissions

To run tests locally, use `make` if you're on Mac or Linux.

1. [ ] Does your submission pass all the tests?
2. [ ] Have you lint your code locally prior to submission?
3. [ ] Have you written proper tests to your added code?

### New Dialog Submissions

User messages have `- -`, bot messages have `  -`

1. [ ] Does all your user messages have lower letters?
2. [ ] Have you lint your dialogs locally prior to submission?
3. [ ] Have you written proper tests to your added dialogs on `test_dialogs`?
4. [ ] Does your dialog have an existing category? If not, did you create it?

### Changes to Core Features

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests or modified old ones for your core changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by alexandrebarbaruiva** [comment]
Remove também a função que estava sendo testada. É para a cobertura de testes manter a mesma, tendo em vista que vc só está removendo funcionalidade

**Comment by vinicius0197** [comment]
@alexandrebarbaruiva Removi a função verify_bot, mas o code coverage continua reclamando. Alguma ideia?

**Comment by alexandrebarbaruiva** [comment]
tá certinho agora, essa diminuição é só pq cada linha de código agora tem uma porcentagem maior

**Comment by alexandrebarbaruiva** [comment]
só melhora a descrição na próxima e marca as questões do template da PR

**Pull request merged**
